### ISSUE TITLE
Letter range scroll should put first entry in range at the top

### ISSUE THREAD

**Issue by JinsuElhance** [calblueprint/dccentralkitchen-clerks#38]
Upon hitting "L-S" on the storefront screen, I would expect that Lemon appears first and that I don't have to scroll down an additional amount to get to the start of the range. 

After clicking T-Z : 
![image](https://user-images.githubusercontent.com/33761390/79676807-9a31eb00-819e-11ea-9ea5-1973c2af029f.png)

**Comment by wangannie** [comment]
Note: seems to be an issue only on smaller devices where the # columns is not 5, because the `alphabeticalScrollTab` algorithm calculates the distance to scroll based on `checkoutNumCols` which is a constant set at 5.
