### ISSUE TITLE
Bug Squash Fang Notes

### ISSUE THREAD

**Issue by dfangshuo** [calblueprint/dccentralkitchen-clerks#40]
1. Loading screen graphic is flashes against the edges of the ipad
2. modal when i click on a grocery item is flushed to the top
3. you have a warning for a lifeCycle method that has been renamed

4. quantity ambiguous - no idea what 4 blueberries mean
5. need to tap on the add twice for it to register -> 1 to dismiss the keyboard, 1 to actually add to cart
6.seeems like it might be helpful to have a way to delete line item explicitly (as opposed to just entering 0)

**Comment by wangannie** [comment]
#52 only addresses number 1 and 2.
