### ISSUE TITLE
Clerk App - Truncates decimal for quantities

### ISSUE THREAD

**Issue by averyyip** [calblueprint/dccentralkitchen-clerks#46]
Potentially a problem for products measured in lbs where the decimal does matter

![Screenshot_20200418-180220_Healthy Corners Clerk](https://user-images.githubusercontent.com/12945091/79676862-5b506500-819f-11ea-9a8c-33b4b59c82a0.jpg)

**Comment by wangannie** [comment]
We never use decimal quantities since all products are priced and sold by the item.
