### ISSUE TITLE
Crashes on login attempts at stores with no registered clerks

### ISSUE THREAD

**Issue by wangannie** [calblueprint/dccentralkitchen-clerks#48]
## what is the name of the screen?

ClerkLoginScreen

## what happened?

As a Clerk, I tried to log into a store that has no registered Clerks

## what did you expect to happen?

I expected the app to gracefully fail (e.g. show a error screen that says  'No clerk found at this store'). Instead, the app crashed.

## are you getting any error message(s)?

![image](https://user-images.githubusercontent.com/21160510/79695334-20940e80-822b-11ea-84a4-dd948db85c9f.png)

## what steps did you take before to get to the error?

1. Select a store that has no registered Clerks (I used Ambo Market)
2. Enter any PIN (it doesn't matter, since there are no clerks registered to verify the PIN against)
3. The app will crash

## Why do you think it happened?

I think it's related to the `const formula` line `getClerksByIds` in request.js. Something fucked up there. The stack trace to get to it: 

- handleSubmit in ClerkLoginScreen →
- lookupClerk in loginUtils →
- getClerksByIds in request.js

Originally submitted [here](https://www.notion.so/Login-bug-in-Clerk-app-a4a5f88303c84660b6394033f825fd91) by @JustinMi

**Comment by anniero98** [comment]
It's a quirk of Airtable - actually the same error as what sometimes crashes Map Screen 😅; it will return fields only if they are non-empty, which is pretty annoying. One-line fix with a condition (check that `clerkIds` is a property of `store`), will fix soon

**Comment by JustinMi** [comment]
yee ty for fixing this
